### ISSUE TITLE
Include pixelsPerMeter as uniform?

### ISSUE THREAD

**Issue by rolyatmax** [tsherif/mercator-gl#7]
Just incorporated `pico-mercator` into the `dlite` project this weekend and found that I needed to slot an additional `pixelsPerMeter` uniform declaration into the vertex source since most of my sketches have needed to do some sort of scaling in world space. This seems like a fairly common use case, so I would imagine many users would end up needing to do the same. I (like you, I'm guessing) am not convinced that this is work pico-mercator should do for the user, but I figured I'd share the feedback.

For reference, the code I end up writing looks like this:

```js
const PIXELS_PER_METER_DECLARATION = `\
uniform float pixelsPerMeter;
`

let vs = pico_mercator_injectGLSLProjection(userVertexSource)
const splitAt = vs.startsWith('#version 300 es') ? vs.indexOf('\n') + 1 : 0
vs = vs.slice(0, splitAt) + PIXELS_PER_METER_DECLARATION + vs.slice(splitAt)

// later, in the render function...

function render (renderArgs) {
  const uniforms = renderArgs.uniforms ? { ...renderArgs.uniforms } : {}
  uniforms.pixelsPerMeter = pico_mercator_pixelsPerMeter(center[1], zoom)
  // still kinda wish this just returned an object 😬
  pico_mercator_uniforms(center, zoom, viewProjMat, (u) => Object.assign(uniforms, u))
  return draw({ ...renderArgs, uniforms })
}
```

**Comment by tsherif** [comment]
Is this still an issue? The uniform API has been fixed for this use case (I think), and you can simply insert the uniform in the base shader code directly ([e.g.](https://github.com/tsherif/mercator-gl/blob/master/examples/scatterplot.html#L64)).

**Comment by rolyatmax** [comment]
I think what you've got now should work fine! Thanks!
