### ISSUE TITLE
Minor func naming feedback

### ISSUE THREAD

**Issue by rolyatmax** [tsherif/mercator-gl#8]
Since it's possible for users to import all exported values from a module under a namespace (one they can choose themselves), I wonder if the `pico_mercator_` prefix is necessary for the exported JavaScript functions.

Just my opinion, but I'd rather do:
```js
const PicoMercator = require('pico-mercator')
PicoMercator.injectGLSLProjection(...)
PicoMercator.mapboxViewProjectionMatrix(...)
PicoMercator.uniforms(...)
```

than:
```js
const {
  pico_mercator_injectGLSLProjection,
  pico_mercator_mapboxViewProjectionMatrix,
  pico_mercator_uniforms
} = require('pico-mercator')
pico_mercator_injectGLSLProjection(...)
pico_mercator_mapboxViewProjectionMatrix(...)
pico_mercator_uniforms(...)
```

Just a minor piece of a feedback from one person - not a big deal either way! :-)

**Comment by tsherif** [comment]
Done!
